---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .ClusterName }}
  name: deploy-wop
data:
    crTemplate: |-
      {
        "apiVersion": "ezkfops.hpe.ezkf-ops.com/v1alpha1",
        "kind": "EzkfWorkloadDeploy",
        "metadata": {
          "name": "{{ .ClusterName }}",
          "namespace": "{{ .ClusterName }}"
        },
        "spec": {
          "deploytarget": "pph",
          "deployenv": "ezkube",
          "workloadtype": "ezua",
          "clustername": "{{ .ClusterName }}",
          "domainname": "{{ .Domain }}",
          "isAirgap": false,
          "deployallinfra": true,
          "genericaddons": {
            "machine": true,
            "ezkube": true
          },
          "proxy": {
            "httpProxy": "{{ .Proxy }}",
            "httpsProxy": "{{ .Proxy }}",
            "noProxy": "{{ .NoProxy }}"
          },
          "workloadaddons": {
            "ua_prep": true,
            "hpecp_agent": true,
            "oidc": true,
            "kyverno": true,
            "monitoring": true,
            "keycloak": true,
            "chartmuseum": true,
            "ezaf_controller": true
          },
          "deployallapps": false,
          "authconfig": {
            "secret_name": "authconfig"
          },
          "airgap": {
            "secret_name": "airgap",
            "registryUrl": "{{ .RegistryUrl }}",
            "registryInsecure": {{ .RegistryInsecure }}
          },
          "apps": {
            "livy": true,
            "ezsql": true,
            "superset": true,
            "feast": true,
            "mlde": false,
            "airflow": true,
            "spark": true,
            "kubeflow": true,
            "mlflow": true,
            "kuberay": true,
            "postInstall": true,
            "appUI": true
          },
          "objectStore": {
            "edfConfig": {
              "endpoint": "https://{{ .DF.S3Nodes }}:9000",
              "secret": "local-s3-secret"
            },
            "provider": "EDF-S3"
          },
          "storage": {
            "edfConfig": {
              "cldbHosts": "{{ .DF.CldbNodes }}",
              "mountPrefix": "/ezua",
              "restServers": "{{ .DF.RestNodes }}",
              "secretName": "local-s3-secret"
            },
            "nfsConfig": {
              "endpoint": "{{ .DF.CldbNodes }}",
              "share": "/mapr/{{ .DF.ClusterName }}/ezua",
              "mountOptions": [
                "vers=3",
                "nolock"
              ]
            },
            "provider": "NFS"
          }
        }
      }
