workload:
  deployTarget: pph
  deployEnv: ezkube
  workloadType: ezua
  clusterName: {{ .ClusterName }}
  resources:
    vcpu: 96
  controlPlaneHostLabels:
    role: controlplane
  workerHostLabels:
    role: worker
  dataFabricHostLabels:
    role: worker
  gpuHostLabels:
    role: worker
  clusterLabels: {}
  controlplane:
    enableHa: false
    controlPlaneEndpoint: {{ .Master }}
  airgap:
    registryUrl: {{ .RegistryUrl }}
    registryInsecure: {{ .RegistryInsecure }}
  network:
    pods:
      cidrBlocks: "10.224.0.0/16"
    serviceDomain: "cluster.local"
    services:
      cidrBlocks: "10.96.0.0/12"
