apiVersion: v1
data:
  registryCaFile:
  userName: {{ .RegistryUsername }}
  password: {{ .RegistryPassword }}
kind: Secret
metadata:
  name: airgap
  namespace: {{ .ClusterName }}
type: Opaque

---
apiVersion: v1
data:
  internal_auth: {{ .AuthData }}
kind: Secret
metadata:
  name: authconfig
  namespace: {{ .ClusterName }}
type: Opaque


---
apiVersion: ezkfops.hpe.ezkf-ops.com/v1alpha1
kind: EzkfWorkloadDeploy
metadata:
  name: {{ .ClusterName }}
  namespace: {{ .ClusterName }}
spec:
  deploytarget: pph
  workloadtype: ezua
  clustername: {{ .ClusterName }}
  domainname: {{ .Domain }}
  isAirgap: false
  deployallinfra: true
  genericaddons:
    machine: true
    ezkube: true
{{if .Proxy }}
  proxy:
    httpProxy: {{ .Proxy }}
    httpsProxy: {{ .Proxy }}
    noProxy: {{ .NoProxy }}
{{end}}
  workloadaddons:
    ua_prep: true
    hpecp_agent: true
    oidc: true
    kyverno: true
    monitoring: true
    keycloak: true
    chartmuseum: true
    ezaf_controller: true
  deployallapps: true # always set to true from UA
  authconfig:
    secret_name: "authconfig"
  airgap:
    secret_name: "airgap"
    registryUrl: {{ .RegistryUrl }}
    registryInsecure: {{ .RegistryInsecure }}
